### ISSUE TITLE
Getting issue while swiping in android pie devices 

### ISSUE THREAD

**Issue by jishantmed** [prabhat1707/VerticalViewPager#3]
I have to swipe till up to make load new page in android 9 devices. Please check

**Comment by prabhat1707** [comment]
thanks for the feedback, let me test it.

**Comment by bhavya92** [comment]
Hey @prabhat1707 @jishantmed , did you find any solution to this long swiping issue ?

**Comment by prabhat1707** [comment]
hi @bhavya92 can u share me some logs or something ?

**Comment by prabhat1707** [comment]
closing this due to non-acticity, bt still found any then open this.
